# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cunfold <- function(Q) {
    .Call(`_nrbfields_cunfold`, Q)
}

copula_field <- function(gridlen, nbasis, l, b, rev) {
    .Call(`_nrbfields_copula_field`, gridlen, nbasis, l, b, rev)
}

